// Auto-generated by OpenLane
module CLB(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input shift_clk,
  output shift_clk_out,
  input shift_data_in,
  output shift_data_out,
  input clk,
  input reset,
  input carry_in,
  input[3:0] horz_bus_in,
  input[3:0] vert_bus_in,
  output clk_out,
  output reset_out,
  output carry_out,
  output[3:0] horz_bus_out,
  output[3:0] vert_bus_out
);
endmodule
